# Example translations file
# Format: <lang>.<key>=<translation>

en.none=All systems are operational
en.minor=Minor restriction
en.major=Major outage
en.critical=Critical failure
en.maintenance=Maintenance work
en.investigating=Will be examined
en.identified=Cause identified
en.monitoring=It is being observed.
en.resolved=Fixed
en.operational=Operational
en.degraded_performance=Limited performance
en.partial_outage=Partial failure
en.major_outage=Severe failure
en.under_maintenance=Maintenance work

de.none=Alle Systeme betriebsbereit
de.minor=Kleinere Einschränkung
de.major=Großer Ausfall
de.critical=Kritischer Fehler
de.maintenance=Wartungsarbeiten
de.investigating=Es wird untersucht
de.identified=Ursache identifiziert
de.monitoring=Es wird beobachtet.
de.resolved=Behoben
de.operational=Betriebsbereit
de.degraded_performance=Eingeschränkte Leistung
de.partial_outage=Teilweiser Ausfall
de.major_outage=Schwerer Ausfall
de.under_maintenance=Wartungsarbeiten
