package com.gerx.statusmonitor;

import java.io.IOException;
import java.io.PrintWriter;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Properties;
import java.util.Scanner;

public class CLI {
    private static final String TRANSLATIONS_EXAMPLE = "# Example translations file\n# Format: <lang>.<key>=<translation>\n\n" +
            "en.none=All systems are operational\n" +
            "en.minor=Minor restriction\n" +
            "en.major=Major outage\n" +
            "en.critical=Critical failure\n" +
            "en.maintenance=Maintenance work\n" +
            "en.investigating=Will be examined\n" +
            "en.identified=Cause identified\n" +
            "en.monitoring=It is being observed.\n" +
            "en.resolved=Fixed\n" +
            "en.operational=Operational\n" +
            "en.degraded_performance=Limited performance\n" +
            "en.partial_outage=Partial failure\n" +
            "en.major_outage=Severe failure\n" +
            "en.under_maintenance=Maintenance work\n\n" +
            "de.none=Alle Systeme betriebsbereit\n" +
            "de.minor=Kleinere Einschränkung\n" +
            "de.major=Großer Ausfall\n" +
            "de.critical=Kritischer Fehler\n" +
            "de.maintenance=Wartungsarbeiten\n" +
            "de.investigating=Es wird untersucht\n" +
            "de.identified=Ursache identifiziert\n" +
            "de.monitoring=Es wird beobachtet.\n" +
            "de.resolved=Behoben\n" +
            "de.operational=Betriebsbereit\n" +
            "de.degraded_performance=Eingeschränkte Leistung\n" +
            "de.partial_outage=Teilweiser Ausfall\n" +
            "de.major_outage=Schwerer Ausfall\n" +
            "de.under_maintenance=Wartungsarbeiten\n";

    public static void main(String[] args) throws IOException {
        Scanner sc = new Scanner(System.in);
        Properties p = new Properties();

        System.out.println("=== Status Monitor Discord Bot - Setup CLI ===");
        System.out.print("Discord Bot Token: ");
        p.setProperty("discord.bot.token", sc.nextLine().trim());

        System.out.print("Statuspage name (the-subdomain before .statuspage.io): ");
        p.setProperty("statuspage.name", sc.nextLine().trim());

        System.out.print("Live status banner URL (or empty): ");
        p.setProperty("banner.live", sc.nextLine().trim());

        System.out.print("History banner URL (or empty): ");
        p.setProperty("banner.history", sc.nextLine().trim());

        System.out.print("Incident channel ID (numeric Discord channel id): ");
        p.setProperty("discord.channel.incident", sc.nextLine().trim());

        System.out.print("Dashboard channel ID (numeric Discord channel id): ");
        p.setProperty("discord.channel.dashboard", sc.nextLine().trim());

        System.out.print("Emoji - operational (e.g. ✅): ");
        p.setProperty("emoji.operational", sc.nextLine().trim());

        System.out.print("Emoji - degraded_performance (e.g. ⚠️): ");
        p.setProperty("emoji.degraded_performance", sc.nextLine().trim());

        System.out.print("Emoji - partial_outage (e.g. 🟠): ");
        p.setProperty("emoji.partial_outage", sc.nextLine().trim());

        System.out.print("Emoji - major_outage (e.g. 🔴): ");
        p.setProperty("emoji.major_outage", sc.nextLine().trim());

        System.out.print("Emoji - maintenance (e.g. 🔵): ");
        p.setProperty("emoji.maintenance", sc.nextLine().trim());

        System.out.print("Check interval seconds (default 300): ");
        String interval = sc.nextLine().trim();
        if (interval.isBlank()) interval = "300";
        p.setProperty("check.interval.seconds", interval);

        System.out.print("Translations file (default lang/translate-example.conf): ");
        String tf = sc.nextLine().trim();
        if (tf.isBlank()) tf = "lang/translate-example.conf";
        p.setProperty("translations.file", tf);

        System.out.print("Translations language (e.g. en or de) (default en): ");
        String lang = sc.nextLine().trim();
        if (lang.isBlank()) lang = "en";
        p.setProperty("translations.language", lang);

        Path cfgFile = Path.of("config.properties");
        try (PrintWriter pw = new PrintWriter(Files.newBufferedWriter(cfgFile))) {
            p.store(pw, "Generated by Status Monitor CLI");
        }

        // write example translations into ./lang if not exists
        Path translations = Path.of(tf);
        if (!Files.exists(translations)) {
            Files.createDirectories(translations.getParent());
            Files.writeString(translations, TRANSLATIONS_EXAMPLE);
        }

        System.out.println("Wrote config.properties and translation file (if not present).");
        System.out.println("You can now run: java -jar target/StatusMonitorDiscordBot-0.1.0-jar-with-dependencies.jar");
    }
}
